### ISSUE TITLE
Words merging

### ISSUE THREAD

**Issue by Amy-Stalter** [Amy-Stalter/more-than-just-datum#1]
Hello! @muxlowc 
Im having some issues with my table data merging together and could use some help!
Thanks!

**Comment by muxlowc** [comment]
@Amy-Stalter  ah, okay so you currently have all of your information in one cell (rather than one row).. so you have:

`<td>545,Play area,Junior,Yes,No,No,No,No</td>`

(TD=Table data, which is basically one cell).. 

So what you actually need to do is this:

```
            <tr>
              <th scope="row">545</th>
              <td>Play area</td>
              <td>Junior</td>
              <td>Yes</td>
              <td>No</td>
              <td>No</td>
              <td>No</td>
              <td>No</td>
            </tr>
```
This is saying that I have 1 row, with 8 points of data within that row.

Hope that helps!

**Comment by Amy-Stalter** [comment]
Thank you!
